---
- name: Ansible Errors Handling
  hosts: all
  any_errors_fatal: true #stop all tasks if eny error
  become: yes

  tasks:
  - name: Task Number1
    yum: name=treeee state=latest
    ignore_errors: yes

  - name: Task Number2
    shell: cat /home/ec2-user/myfile.txt
    register: results  #save echo output in results var
    # failed_when: "'World' in results.stdout"
    # failed_when: results.rc == 0

  - debug:
      var: results     #print results

  - name: Task Number3
    shell: echo Privet world

